version: '3.5'
services:
# main application gurume
  gurume:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SSH_KEY
    environment:
      - GURUME_ENV=${GURUME_ENV}
      - ES_CLUSTER_HOST=${ES_CLUSTER_HOST}
      - ES_CLUSTER_PORT=${ES_CLUSTER_PORT}
      - ES_CLUSTER_USER_ID=${ES_CLUSTER_USER_ID}
      - ES_CLUSTER_USER_PW=${ES_CLUSTER_USER_PW}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./data:/tmp/data
    networks:
      - gurumenet
# elasticsearch cluster
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=catalog-es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/userdict_ko.txt:/usr/share/elasticsearch/config/userdict_ko.txt
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - gurumenet
  elasticsearch2:
    build: ./elasticsearch
    container_name: elasticsearch2
    environment:
      - node.name=es02
      - cluster.name=catalog-es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/userdict_ko.txt:/usr/share/elasticsearch/config/userdict_ko.txt
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - gurumenet
  elasticsearch3:
    build: ./elasticsearch
    container_name: elasticsearch3
    environment:
      - node.name=es03
      - cluster.name=catalog-es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/userdict_ko.txt:/usr/share/elasticsearch/config/userdict_ko.txt
      - esdata3:/usr/share/elasticsearch/data
    networks:
      - gurumenet
# kibana
  kibana:
    build: ./kibana
    container_name: gurume-kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - 5601:5601
    networks:
      - gurumenet
# volumes
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
# networks
networks:
  gurumenet: